export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

export const LOAD_DISCOUNT_CODES_SUCCESS = 'LOAD_DISCOUNT_CODES_SUCCESS';

export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
