export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';

export const LOAD_DISCOUNT_CODES_SUCCESS = 'LOAD_DISCOUNT_CODES_SUCCESS';

export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
export const CLEAR_CART = 'CLEAR_CART';
